import { PrismaClient } from '../server/node_modules/.prisma/client';

process.env['DATABASE_URL'] = 'file:../data/dentalai.db';

const prisma = new PrismaClient();

async function main() {
  console.log('Seeding DentalAI database...');

  // ─── Providers ────────────────────────────────────────────────────────────
  const providers = await Promise.all([
    prisma.provider.upsert({
      where: { id: 'prov-mitchell' },
      update: {},
      create: {
        id: 'prov-mitchell',
        firstName: 'Sarah',
        lastName: 'Mitchell',
        title: 'DDS',
        specialty: 'General Dentistry',
      },
    }),
    prisma.provider.upsert({
      where: { id: 'prov-patel' },
      update: {},
      create: {
        id: 'prov-patel',
        firstName: 'James',
        lastName: 'Patel',
        title: 'DMD',
        specialty: 'Periodontology',
      },
    }),
    prisma.provider.upsert({
      where: { id: 'prov-ross' },
      update: {},
      create: {
        id: 'prov-ross',
        firstName: 'Jennifer',
        lastName: 'Ross',
        title: 'RDH',
        specialty: 'Dental Hygiene',
      },
    }),
  ]);

  const [mitchell, patel, ross] = providers;
  console.log(`Created ${providers.length} providers`);

  // ─── Patients ─────────────────────────────────────────────────────────────
  const patientData = [
    {
      id: 'pat-001',
      firstName: 'Margaret',
      lastName: 'Harrington',
      dateOfBirth: '1968-03-14',
      phone: '(312) 555-0142',
      email: 'margaret.harrington@email.com',
      preferredContactMethod: 'email',
      lastCleaningDate: '2023-07-18',
      recallDueDate: '2024-01-18',
      insuranceProvider: 'Delta Dental',
      memberId: 'DD-8821445',
      outstandingBalance: 215.0,
      providerId: mitchell.id,
    },
    {
      id: 'pat-002',
      firstName: 'Robert',
      lastName: 'Kessler',
      dateOfBirth: '1955-11-02',
      phone: '(312) 555-0287',
      email: 'r.kessler@workplace.com',
      preferredContactMethod: 'phone',
      lastCleaningDate: '2023-04-05',
      recallDueDate: '2023-10-05',
      insuranceProvider: 'Cigna Dental',
      memberId: 'CIG-3347821',
      outstandingBalance: 480.5,
      providerId: patel.id,
    },
    {
      id: 'pat-003',
      firstName: 'Aisha',
      lastName: 'Washington',
      dateOfBirth: '1990-06-27',
      phone: '(773) 555-0391',
      email: 'aisha.washington@gmail.com',
      preferredContactMethod: 'email',
      lastCleaningDate: '2024-01-10',
      recallDueDate: '2024-07-10',
      insuranceProvider: 'Aetna Dental',
      memberId: 'AET-5592038',
      outstandingBalance: 0,
      providerId: mitchell.id,
    },
    {
      id: 'pat-004',
      firstName: 'Thomas',
      lastName: 'Brennan',
      dateOfBirth: '1975-09-18',
      phone: '(630) 555-0458',
      email: 'tbrennan@hotmail.com',
      preferredContactMethod: 'text',
      lastCleaningDate: '2023-05-22',
      recallDueDate: '2023-11-22',
      insuranceProvider: 'MetLife Dental',
      memberId: 'MET-7734902',
      outstandingBalance: 135.0,
      providerId: ross.id,
    },
    {
      id: 'pat-005',
      firstName: 'Linda',
      lastName: 'Castillo',
      dateOfBirth: '1962-01-09',
      phone: '(847) 555-0512',
      email: 'linda.castillo@yahoo.com',
      preferredContactMethod: 'email',
      lastCleaningDate: '2023-08-14',
      recallDueDate: '2024-02-14',
      insuranceProvider: 'Blue Cross Dental',
      memberId: 'BCBS-2290183',
      outstandingBalance: 650.75,
      providerId: mitchell.id,
    },
    {
      id: 'pat-006',
      firstName: 'David',
      lastName: 'Nguyen',
      dateOfBirth: '1988-04-03',
      phone: '(312) 555-0614',
      email: 'david.nguyen@company.org',
      preferredContactMethod: 'email',
      lastCleaningDate: '2024-02-05',
      recallDueDate: '2024-08-05',
      insuranceProvider: 'Delta Dental',
      memberId: 'DD-4473829',
      outstandingBalance: 0,
      providerId: patel.id,
    },
    {
      id: 'pat-007',
      firstName: 'Patricia',
      lastName: 'Monroe',
      dateOfBirth: '1971-12-30',
      phone: '(708) 555-0723',
      email: 'pat.monroe@email.net',
      preferredContactMethod: 'phone',
      lastCleaningDate: '2023-03-11',
      recallDueDate: '2023-09-11',
      insuranceProvider: 'Cigna Dental',
      memberId: 'CIG-8819023',
      outstandingBalance: 320.0,
      providerId: mitchell.id,
    },
    {
      id: 'pat-008',
      firstName: 'Kevin',
      lastName: 'Okafor',
      dateOfBirth: '1983-07-22',
      phone: '(773) 555-0834',
      email: 'kevin.okafor@gmail.com',
      preferredContactMethod: 'text',
      lastCleaningDate: '2023-09-28',
      recallDueDate: '2024-03-28',
      insuranceProvider: 'Aetna Dental',
      memberId: 'AET-6611245',
      outstandingBalance: 95.0,
      providerId: ross.id,
    },
    {
      id: 'pat-009',
      firstName: 'Susan',
      lastName: 'Whitfield',
      dateOfBirth: '1959-05-16',
      phone: '(847) 555-0945',
      email: 'swhitfield@outlook.com',
      preferredContactMethod: 'email',
      lastCleaningDate: '2023-06-03',
      recallDueDate: '2023-12-03',
      insuranceProvider: 'MetLife Dental',
      memberId: 'MET-3321567',
      outstandingBalance: 0,
      providerId: patel.id,
    },
    {
      id: 'pat-010',
      firstName: 'Carlos',
      lastName: 'Ramirez',
      dateOfBirth: '1992-10-11',
      phone: '(312) 555-1023',
      email: 'carlos.ramirez@mail.com',
      preferredContactMethod: 'text',
      lastCleaningDate: '2024-01-22',
      recallDueDate: '2024-07-22',
      insuranceProvider: 'Delta Dental',
      memberId: 'DD-9987431',
      outstandingBalance: 0,
      providerId: mitchell.id,
    },
    {
      id: 'pat-011',
      firstName: 'Emily',
      lastName: 'Thornton',
      dateOfBirth: '1947-08-04',
      phone: '(630) 555-1134',
      email: 'emily.thornton@comcast.net',
      preferredContactMethod: 'phone',
      lastCleaningDate: '2023-02-08',
      recallDueDate: '2023-08-08',
      insuranceProvider: 'Blue Cross Dental',
      memberId: 'BCBS-5544312',
      outstandingBalance: 890.0,
      providerId: patel.id,
    },
    {
      id: 'pat-012',
      firstName: 'Jason',
      lastName: 'Park',
      dateOfBirth: '2001-03-25',
      phone: '(773) 555-1245',
      email: 'jpark2001@gmail.com',
      preferredContactMethod: 'text',
      lastCleaningDate: '2024-03-01',
      recallDueDate: '2024-09-01',
      insuranceProvider: 'Cigna Dental',
      memberId: 'CIG-1123456',
      outstandingBalance: 0,
      providerId: ross.id,
    },
  ];

  for (const p of patientData) {
    await prisma.patient.upsert({ where: { id: p.id }, update: p, create: p });
  }
  console.log(`Created ${patientData.length} patients`);

  // ─── Appointments ─────────────────────────────────────────────────────────
  const appointmentData = [
    // Past completed
    {
      id: 'appt-001',
      patientId: 'pat-001',
      providerId: ross.id,
      date: '2023-07-18',
      time: '09:00',
      duration: 60,
      type: 'Hygiene - Adult Prophy',
      status: 'completed',
      notes: 'Routine 6-month cleaning completed without issues.',
    },
    {
      id: 'appt-002',
      patientId: 'pat-002',
      providerId: patel.id,
      date: '2023-04-05',
      time: '14:00',
      duration: 90,
      type: 'Periodontal Maintenance',
      status: 'completed',
      notes: 'SRP lower arch — patient tolerated well.',
    },
    {
      id: 'appt-003',
      patientId: 'pat-003',
      providerId: ross.id,
      date: '2024-01-10',
      time: '10:30',
      duration: 60,
      type: 'Hygiene - Adult Prophy',
      status: 'completed',
      notes: 'BOP minimal. FMX reviewed, no new caries.',
    },
    {
      id: 'appt-004',
      patientId: 'pat-004',
      providerId: mitchell.id,
      date: '2023-05-22',
      time: '11:00',
      duration: 45,
      type: 'Restorative - Composite',
      status: 'completed',
      notes: 'Composite restoration #14 MO completed.',
    },
    {
      id: 'appt-005',
      patientId: 'pat-005',
      providerId: mitchell.id,
      date: '2023-08-14',
      time: '08:30',
      duration: 120,
      type: 'Restorative - Crown Prep',
      status: 'completed',
      notes: 'Crown prep #3 — temporary placed, impressions sent to lab.',
    },
    {
      id: 'appt-006',
      patientId: 'pat-006',
      providerId: patel.id,
      date: '2024-02-05',
      time: '15:30',
      duration: 60,
      type: 'Periodontal Re-evaluation',
      status: 'completed',
      notes: 'Perio re-eval post SRP — excellent response, probing depths improved.',
    },
    {
      id: 'appt-007',
      patientId: 'pat-007',
      providerId: mitchell.id,
      date: '2023-03-11',
      time: '09:30',
      duration: 90,
      type: 'Comprehensive Exam + Cleaning',
      status: 'completed',
      notes: 'New patient comprehensive exam. Multiple restorative needs identified.',
    },
    {
      id: 'appt-008',
      patientId: 'pat-008',
      providerId: ross.id,
      date: '2023-09-28',
      time: '13:00',
      duration: 60,
      type: 'Hygiene - Adult Prophy',
      status: 'completed',
      notes: 'Routine cleaning. Noted calculus buildup mandibular anteriors.',
    },
    {
      id: 'appt-009',
      patientId: 'pat-009',
      providerId: patel.id,
      date: '2023-06-03',
      time: '10:00',
      duration: 90,
      type: 'Periodontal Maintenance',
      status: 'completed',
      notes: 'Quarterly perio maintenance — stable.',
    },
    {
      id: 'appt-010',
      patientId: 'pat-010',
      providerId: ross.id,
      date: '2024-01-22',
      time: '08:00',
      duration: 60,
      type: 'Hygiene - Adult Prophy',
      status: 'completed',
      notes: 'BWX taken. No new pathology. Good home care.',
    },
    {
      id: 'appt-011',
      patientId: 'pat-011',
      providerId: patel.id,
      date: '2023-02-08',
      time: '14:30',
      duration: 120,
      type: 'Periodontal SRP',
      status: 'completed',
      notes: 'Full-mouth SRP. High bacterial load, smoking habit noted.',
    },
    {
      id: 'appt-012',
      patientId: 'pat-012',
      providerId: ross.id,
      date: '2024-03-01',
      time: '16:00',
      duration: 45,
      type: 'Hygiene - Adolescent Prophy',
      status: 'completed',
      notes: 'Sealants recommended on #1, #16, #17, #32. Discussed with parent.',
    },
    // Upcoming scheduled
    {
      id: 'appt-013',
      patientId: 'pat-001',
      providerId: mitchell.id,
      date: '2026-04-15',
      time: '10:00',
      duration: 60,
      type: 'Restorative - Composite',
      status: 'scheduled',
      notes: 'Composite #18 MO — patient notified.',
    },
    {
      id: 'appt-014',
      patientId: 'pat-003',
      providerId: ross.id,
      date: '2026-04-18',
      time: '09:00',
      duration: 60,
      type: 'Hygiene - Adult Prophy',
      status: 'scheduled',
      notes: '6-month recall.',
    },
    {
      id: 'appt-015',
      patientId: 'pat-005',
      providerId: mitchell.id,
      date: '2026-04-20',
      time: '11:00',
      duration: 90,
      type: 'Restorative - Crown Seat',
      status: 'scheduled',
      notes: 'Crown seat #3 — lab work confirmed in.',
    },
    {
      id: 'appt-016',
      patientId: 'pat-010',
      providerId: mitchell.id,
      date: '2026-04-22',
      time: '14:00',
      duration: 60,
      type: 'Emergency - Pain Evaluation',
      status: 'scheduled',
      notes: 'Patient called reporting pain lower right — evaluate #30, #31.',
    },
    {
      id: 'appt-017',
      patientId: 'pat-006',
      providerId: patel.id,
      date: '2026-04-25',
      time: '15:00',
      duration: 90,
      type: 'Periodontal Maintenance',
      status: 'scheduled',
      notes: 'Quarterly maintenance.',
    },
    {
      id: 'appt-018',
      patientId: 'pat-008',
      providerId: ross.id,
      date: '2026-04-28',
      time: '08:30',
      duration: 60,
      type: 'Hygiene - Adult Prophy',
      status: 'scheduled',
      notes: '6-month recall overdue.',
    },
  ];

  for (const a of appointmentData) {
    await prisma.appointment.upsert({ where: { id: a.id }, update: a, create: a });
  }
  console.log(`Created ${appointmentData.length} appointments`);

  // ─── Clinical Notes ────────────────────────────────────────────────────────
  const noteData = [
    {
      id: 'note-001',
      patientId: 'pat-001',
      appointmentId: 'appt-001',
      providerId: ross.id,
      date: '2023-07-18',
      transcript: 'Patient came in for her regular cleaning. No pain or sensitivity reported. She mentioned she has been flossing more regularly.',
      subjective: 'Patient Margaret Harrington presents for routine 6-month hygiene appointment. No chief complaints. Reports improved home care — flossing daily for the past 3 months. No sensitivity or discomfort noted.',
      objective: 'Extra-oral exam: WNL. Intra-oral exam: Good oral hygiene — plaque index 8%. Minimal supragingival calculus on mandibular anteriors. BOP: 12% — mild gingivitis localized to posterior interproximals. Probing depths: 2-3mm throughout. BWX reviewed — no caries, stable crestal bone levels.',
      assessment: 'Mild localized gingivitis, otherwise healthy dentition. Excellent improvement in home care compliance.',
      plan: 'Adult prophylaxis completed (D1110). Selective scaling mandibular anteriors. Fluoride varnish applied. Reinforced flossing technique — recommended WaterFlosser for posterior access. Recall in 6 months.',
      status: 'approved',
      procedureCode: 'D1110',
      toothNumbers: null,
    },
    {
      id: 'note-002',
      patientId: 'pat-002',
      appointmentId: 'appt-002',
      providerId: patel.id,
      date: '2023-04-05',
      transcript: 'Patient has been having trouble with his gums bleeding when he brushes. He says it is worse in the mornings. He smokes about 10 cigarettes a day.',
      subjective: 'Patient Robert Kessler presents for SRP lower arch. Reports persistent gingival bleeding on brushing, worse in the AM. Smokes 10 cigarettes/day — cessation counseling attempted. Compliance with home care described as inconsistent.',
      objective: 'Periodontal charting: Generalized probing depths 4-7mm, lower arch. BOP: 72%. Furcation Class I on #19, #30. Heavy subgingival calculus deposits LL and LR quadrants. Radiographic horizontal bone loss 20-35% lower posterior. No mobility noted.',
      assessment: 'Generalized severe chronic periodontitis, lower arch. Exacerbated by tobacco use and suboptimal home care. Bleeding on probing consistent with active disease.',
      plan: 'Full-mouth SRP in two quadrants (LL, LR) today under 3 carpules 2% lidocaine 1:100k epi. Prescribed chlorhexidine gluconate 0.12% rinse BID x 2 weeks. Smoking cessation referral given. Arestin microspheres placed at #19 MB, #30 DB. Re-evaluation in 4-6 weeks. Remaining upper arch scheduled.',
      status: 'approved',
      procedureCode: 'D4341',
      toothNumbers: '18,19,30,31',
    },
    {
      id: 'note-003',
      patientId: 'pat-003',
      appointmentId: 'appt-003',
      providerId: ross.id,
      date: '2024-01-10',
      transcript: 'Just a regular checkup and cleaning for Aisha. She is doing really well, great brusher, no issues to report.',
      subjective: 'Patient Aisha Washington presents for 6-month hygiene recall. No complaints. Excellent home care compliance — brushes twice daily with electric toothbrush and flosses nightly.',
      objective: 'Extra-oral: WNL. Intra-oral: Excellent oral hygiene — plaque index 4%. No calculus visible. BOP: 3% — 2 isolated bleeding points at #2, #15 distal. Probing depths: 2-3mm throughout. FMX reviewed — no caries, no periapical pathology, stable bone levels.',
      assessment: 'Healthy periodontium, no caries. Patient in excellent oral health.',
      plan: 'Adult prophylaxis completed (D1110). Polished with fine paste. Fluoride varnish applied. Reviewed FMX with patient — all WNL. Recommended continued excellent home care. Recall 6 months.',
      status: 'approved',
      procedureCode: 'D1110',
      toothNumbers: null,
    },
    {
      id: 'note-004',
      patientId: 'pat-004',
      appointmentId: 'appt-004',
      providerId: mitchell.id,
      date: '2023-05-22',
      transcript: 'Thomas was here for the filling on the upper left molar. He was a little nervous but did fine. The decay was moderate in depth.',
      subjective: 'Patient Thomas Brennan presents for composite restoration #14 MO. No current pain. Reports mild dental anxiety — managed with tell-show-do and oral hygiene discussion during setup.',
      objective: 'Pre-op radiograph confirms moderate carious lesion #14 MO. Tooth vital, percussion WNL. Soft tissue: WNL.',
      assessment: 'Moderate carious lesion #14 MO (D2 — enamel and dentin). No pulpal involvement suspected.',
      plan: 'Local anesthesia: 1.8mL 4% articaine 1:100k epi inferior alveolar block + buccal infiltration. Caries removed with 330 bur — dentin exposed, no pulpal bleed. Dentin bonding agent applied per protocol. Composite resin layered and cured. Occlusion adjusted. Post-op: no sensitivity expected. Patient given post-op instructions. Follow up PRN.',
      status: 'approved',
      procedureCode: 'D2391',
      toothNumbers: '14',
    },
    {
      id: 'note-005',
      patientId: 'pat-005',
      appointmentId: 'appt-005',
      providerId: mitchell.id,
      date: '2023-08-14',
      transcript: 'Linda came in for the crown prep on tooth 3. She reported some sensitivity to cold before the appointment. The prep went well, we placed the temporary.',
      subjective: 'Patient Linda Castillo presents for crown preparation #3. Reports preoperative cold sensitivity, 2/10 pain, resolves within 5 seconds. No spontaneous pain. Previous composite #3 placed 3 years ago now with secondary decay.',
      objective: 'Pre-op radiograph: secondary caries under existing composite #3 MOD, caries approaching pulp. Cold test: normal response, no prolonged sensitivity today. Percussion: WNL. Probing depths #3: WNL.',
      assessment: 'Secondary carious lesion under existing restoration #3 MOD. Pulp appears vital — crown indicated to restore and protect remaining tooth structure. Crack lines noted on transillumination on buccal cusps.',
      plan: 'Crown preparation #3 completed — PFM crown indicated. 2 carpules 4% articaine 1:100k epi PSA + MSA blocks. Secondary caries removed with carbide burs, base of dentin conditioner applied. Feather-edge margins refined. Polyvinyl siloxane impression taken — final impression satisfactory, sent to lab (Jensen Dental). Provisional crown fabricated with bis-acryl, cemented with Temp-Bond. Post-op: avoid sticky foods on temp. Seat appointment in 2 weeks.',
      status: 'pending_approval',
      procedureCode: 'D2750',
      toothNumbers: '3',
    },
    {
      id: 'note-006',
      patientId: 'pat-006',
      appointmentId: 'appt-006',
      providerId: patel.id,
      date: '2024-02-05',
      transcript: 'David had his re-eval after the SRP. His pockets have reduced significantly. He has been doing the home care routine we recommended.',
      subjective: 'Patient David Nguyen presents for periodontal re-evaluation 6 weeks post full-mouth SRP. No complaints. Reports consistent use of prescribed chlorhexidine rinse and improved home care — sonic toothbrush and water flosser in use.',
      objective: 'Full-mouth periodontal charting: Significant improvement — probing depths reduced from 5-8mm to 3-4mm throughout. BOP: 22% (down from 58%). Tissue color improved — less erythema and edema. Furcation involvement reduced to Class I at #3, #14. No new calculus deposits.',
      assessment: 'Excellent response to periodontal therapy. Generalized chronic periodontitis, resolving. Tissue demonstrates healing and regeneration consistent with successful treatment.',
      plan: 'No additional SRP at this time. Transition to 3-month periodontal maintenance (D4910). Re-chart in 6 months. Continue chlorhexidine rinse 1x/day as maintenance. Reinforce home care. Patient educated on long-term periodontal health maintenance.',
      status: 'approved',
      procedureCode: 'D4910',
      toothNumbers: null,
    },
    {
      id: 'note-007',
      patientId: 'pat-007',
      appointmentId: 'appt-007',
      providerId: mitchell.id,
      date: '2023-03-11',
      transcript: 'New patient, Patricia Monroe. She has not been to the dentist in over 4 years. She reports her lower right molar has been bothering her for a few weeks but no emergency today.',
      subjective: 'New patient Patricia Monroe presents for comprehensive examination. Last dental visit approximately 4 years ago. Reports intermittent discomfort LR quadrant x 3 weeks — 3/10 pain, cold-provoked, resolves in <10 seconds. No spontaneous pain, no swelling. No significant medical history. NKDA. No current medications.',
      objective: 'Extra-oral exam: No lymphadenopathy, no facial asymmetry, TMJ WNL. Intra-oral: Moderate plaque and calculus. Multiple existing amalgam restorations — several with marginal defects. Tooth #30: large existing amalgam, craze lines visible, cold test positive with 8-second lingering response. Radiographs (FMX + pano): carious lesion #28 DO, secondary caries under amalgam #30, no periapical pathology.',
      assessment: '1. Deep carious lesion #30 with possible pulpal involvement — rule out irreversible pulpitis. 2. Carious lesion #28 DO. 3. Multiple defective restorations — treatment planning needed. 4. Moderate generalized gingivitis.',
      plan: '1. Referred to endodontic consult for #30 — possible RCT vs. extraction discussion. 2. Composite restoration #28 DO scheduled next visit. 3. Periodontal prophylaxis completed today (D1110). 4. Radiographic series on file. 5. Full treatment plan presented and discussed — patient agreeable. 6. Rx: Ibuprofen 400mg TID PRN for pain management until further treatment.',
      status: 'pending_approval',
      procedureCode: 'D0150',
      toothNumbers: '28,30',
    },
    {
      id: 'note-008',
      patientId: 'pat-008',
      appointmentId: 'appt-008',
      providerId: ross.id,
      date: '2023-09-28',
      transcript: 'Kevin came in for his cleaning. He mentioned he drinks a lot of energy drinks and coffee. His front teeth have some staining.',
      subjective: 'Patient Kevin Okafor presents for routine 6-month hygiene appointment. No complaints. Reports heavy coffee and energy drink consumption — 3-4 cups per day. No tobacco use.',
      objective: 'Extra-oral: WNL. Intra-oral: Moderate extrinsic staining — anterior facial surfaces. Heavy supragingival calculus mandibular lingual anterior (calculus bridge). Moderate subgingival calculus UR and UL posteriors. BOP: 28%. Probing depths: 2-4mm, no sites >4mm. Plaque index: 32%.',
      assessment: 'Moderate plaque-induced gingivitis with extrinsic staining secondary to dietary habits. Calculus accumulation significant.',
      plan: 'Adult prophylaxis (D1110) with selective hand scaling to remove heavy deposits. Ultrasonic scaling used on calculus bridge. Polished with medium pumice paste followed by fine. Whitening options discussed — in-office and take-home reviewed, patient interested. Fluoride varnish applied. Recall 6 months. Dietary counseling given — advised to rinse after coffee/energy drinks.',
      status: 'draft',
      procedureCode: 'D1110',
      toothNumbers: null,
    },
    {
      id: 'note-009',
      patientId: 'pat-011',
      appointmentId: 'appt-011',
      providerId: patel.id,
      date: '2023-02-08',
      transcript: 'Emily had her full mouth SRP today. She has advanced periodontal disease. Very heavy smoker, a pack a day. We treated upper arch today.',
      subjective: 'Patient Emily Thornton presents for periodontal SRP — upper arch. Chief complaint: loose upper teeth x 6 months, bad breath. Smokes 1 ppd x 35 years. Medical Hx: HTN (Lisinopril 10mg), Type 2 DM (Metformin 500mg) — A1c 7.8% per PCP report. No known drug allergies.',
      objective: 'Full-mouth periodontal charting: Generalized probing depths 6-10mm. Multiple furcation involvements Class II-III on #2, #3, #14, #15. Significant tooth mobility: Class II #1, #16. Radiographic evidence: generalized severe bone loss 40-70%. Heavy subgingival calculus upper arch. BOP: 89%.',
      assessment: 'Generalized severe chronic periodontitis with significant attachment loss and bone destruction. Exacerbated by uncontrolled DM, tobacco use, and poor home care compliance. Guarded prognosis for posterior teeth with Class II-III furcations.',
      plan: 'Upper arch SRP completed in two quadrants (UR, UL) under 4 carpules 2% lidocaine 1:100k epi. 4 Arestin microsphere placements at deepest pockets. Chlorhexidine 0.12% BID x 2 weeks. Cessation counseling given — nicotine patch referral provided. Coordinating with PCP regarding glycemic control — letter sent. Lower arch SRP to be scheduled. Prognosis discussed with patient — extraction of #1, #16 may be necessary.',
      status: 'approved',
      procedureCode: 'D4341',
      toothNumbers: '1,2,3,14,15,16',
    },
    {
      id: 'note-010',
      patientId: 'pat-012',
      appointmentId: 'appt-012',
      providerId: ross.id,
      date: '2024-03-01',
      transcript: 'Jason is a young patient, 23 years old. Had his teeth cleaned today. We discussed some decay we noticed on the xrays and recommended sealants on the wisdom teeth.',
      subjective: 'Patient Jason Park presents for 6-month hygiene appointment. No complaints. Reports brushing once daily — encouraged to brush twice. No flossing habit. Diet: high in sugary beverages.',
      objective: 'Extra-oral: WNL. Intra-oral: Moderate plaque accumulation. Gingival tissues mildly inflamed with erythema and slight edema. BOP: 35%. Probing depths: 2-3mm. Bitewing radiographs: incipient lesions #30 MO (D1), #31 MO (D1) — watch and wait. Enamel grooves on all four third molars fully erupted.',
      assessment: 'Plaque-induced gingivitis. Incipient carious lesions #30, #31 — monitoring. Deep occlusal grooves on #1, #16, #17, #32 — sealant candidates.',
      plan: 'Adult prophylaxis completed (D1110). Fluoride varnish applied. Sealants recommended on #1, #16, #17, #32 — scheduled for next visit. Dietary counseling: advised to reduce sugar-sweetened beverages, use straw. Demonstrated proper brushing technique — recommended 2-minute timer. Recall 6 months. Parent/guardian (patient is 23, self-consenting) notified of treatment recommendations.',
      status: 'draft',
      procedureCode: 'D1110',
      toothNumbers: '30,31',
    },
  ];

  for (const n of noteData) {
    await prisma.clinicalNote.upsert({ where: { id: n.id }, update: n, create: n });
  }
  console.log(`Created ${noteData.length} clinical notes`);

  // ─── Insurance Plans ───────────────────────────────────────────────────────
  const planData = [
    {
      id: 'plan-001',
      patientId: 'pat-001',
      provider: 'Delta Dental',
      memberId: 'DD-8821445',
      groupNumber: 'GRP-441209',
      deductible: 100,
      deductibleMet: 100,
      annualMax: 2000,
      annualUsed: 620,
      verificationStatus: 'verified',
      verifiedDate: '2024-01-02',
      coPayPreventive: 0,
      coPayBasic: 20,
      coPayMajor: 50,
    },
    {
      id: 'plan-002',
      patientId: 'pat-002',
      provider: 'Cigna Dental',
      memberId: 'CIG-3347821',
      groupNumber: 'GRP-882341',
      deductible: 150,
      deductibleMet: 150,
      annualMax: 1500,
      annualUsed: 1340,
      verificationStatus: 'verified',
      verifiedDate: '2024-01-05',
      coPayPreventive: 0,
      coPayBasic: 20,
      coPayMajor: 50,
    },
    {
      id: 'plan-003',
      patientId: 'pat-003',
      provider: 'Aetna Dental',
      memberId: 'AET-5592038',
      groupNumber: 'GRP-209341',
      deductible: 50,
      deductibleMet: 50,
      annualMax: 2500,
      annualUsed: 195,
      verificationStatus: 'verified',
      verifiedDate: '2024-01-10',
      coPayPreventive: 0,
      coPayBasic: 15,
      coPayMajor: 40,
    },
    {
      id: 'plan-004',
      patientId: 'pat-004',
      provider: 'MetLife Dental',
      memberId: 'MET-7734902',
      groupNumber: 'GRP-331892',
      deductible: 75,
      deductibleMet: 75,
      annualMax: 1750,
      annualUsed: 520,
      verificationStatus: 'pending',
      verifiedDate: null,
      coPayPreventive: 0,
      coPayBasic: 20,
      coPayMajor: 50,
    },
    {
      id: 'plan-005',
      patientId: 'pat-005',
      provider: 'Blue Cross Dental',
      memberId: 'BCBS-2290183',
      groupNumber: 'GRP-778123',
      deductible: 100,
      deductibleMet: 100,
      annualMax: 3000,
      annualUsed: 1820,
      verificationStatus: 'verified',
      verifiedDate: '2024-01-08',
      coPayPreventive: 0,
      coPayBasic: 20,
      coPayMajor: 50,
    },
    {
      id: 'plan-006',
      patientId: 'pat-006',
      provider: 'Delta Dental',
      memberId: 'DD-4473829',
      groupNumber: 'GRP-990123',
      deductible: 100,
      deductibleMet: 100,
      annualMax: 2000,
      annualUsed: 880,
      verificationStatus: 'verified',
      verifiedDate: '2024-02-01',
      coPayPreventive: 0,
      coPayBasic: 20,
      coPayMajor: 50,
    },
    {
      id: 'plan-007',
      patientId: 'pat-007',
      provider: 'Cigna Dental',
      memberId: 'CIG-8819023',
      groupNumber: 'GRP-556712',
      deductible: 150,
      deductibleMet: 75,
      annualMax: 1500,
      annualUsed: 195,
      verificationStatus: 'pending',
      verifiedDate: null,
      coPayPreventive: 0,
      coPayBasic: 20,
      coPayMajor: 50,
    },
    {
      id: 'plan-008',
      patientId: 'pat-008',
      provider: 'Aetna Dental',
      memberId: 'AET-6611245',
      groupNumber: 'GRP-441023',
      deductible: 50,
      deductibleMet: 50,
      annualMax: 2000,
      annualUsed: 195,
      verificationStatus: 'verified',
      verifiedDate: '2024-01-15',
      coPayPreventive: 0,
      coPayBasic: 15,
      coPayMajor: 40,
    },
    {
      id: 'plan-009',
      patientId: 'pat-009',
      provider: 'MetLife Dental',
      memberId: 'MET-3321567',
      groupNumber: 'GRP-118923',
      deductible: 75,
      deductibleMet: 75,
      annualMax: 1750,
      annualUsed: 1100,
      verificationStatus: 'verified',
      verifiedDate: '2023-12-28',
      coPayPreventive: 0,
      coPayBasic: 20,
      coPayMajor: 50,
    },
    {
      id: 'plan-010',
      patientId: 'pat-010',
      provider: 'Delta Dental',
      memberId: 'DD-9987431',
      groupNumber: 'GRP-882019',
      deductible: 100,
      deductibleMet: 100,
      annualMax: 2000,
      annualUsed: 195,
      verificationStatus: 'verified',
      verifiedDate: '2024-01-20',
      coPayPreventive: 0,
      coPayBasic: 20,
      coPayMajor: 50,
    },
    {
      id: 'plan-011',
      patientId: 'pat-011',
      provider: 'Blue Cross Dental',
      memberId: 'BCBS-5544312',
      groupNumber: 'GRP-221456',
      deductible: 100,
      deductibleMet: 100,
      annualMax: 2500,
      annualUsed: 2500,
      verificationStatus: 'verified',
      verifiedDate: '2023-12-15',
      coPayPreventive: 0,
      coPayBasic: 20,
      coPayMajor: 50,
    },
    {
      id: 'plan-012',
      patientId: 'pat-012',
      provider: 'Cigna Dental',
      memberId: 'CIG-1123456',
      groupNumber: 'GRP-774321',
      deductible: 50,
      deductibleMet: 50,
      annualMax: 1500,
      annualUsed: 195,
      verificationStatus: 'verified',
      verifiedDate: '2024-03-01',
      coPayPreventive: 0,
      coPayBasic: 15,
      coPayMajor: 40,
    },
  ];

  for (const p of planData) {
    await prisma.insurancePlan.upsert({ where: { id: p.id }, update: p, create: p });
  }
  console.log(`Created ${planData.length} insurance plans`);

  // ─── Insurance Claims ──────────────────────────────────────────────────────
  const claimData = [
    {
      id: 'claim-001',
      patientId: 'pat-001',
      insurancePlanId: 'plan-001',
      appointmentId: 'appt-001',
      claimDate: '2023-07-20',
      procedureCodes: 'D1110,D0220',
      totalAmount: 195.0,
      narrative: 'Adult prophylaxis including supragingival scaling, polishing, and fluoride varnish. Periapical radiograph taken of #18 due to patient-reported sensitivity. No acute pathology identified on radiograph.',
      status: 'approved',
      submittedDate: '2023-07-20',
      approvedAmount: 175.5,
      denialReason: null,
    },
    {
      id: 'claim-002',
      patientId: 'pat-002',
      insurancePlanId: 'plan-002',
      appointmentId: 'appt-002',
      claimDate: '2023-04-07',
      procedureCodes: 'D4341,D4381',
      totalAmount: 820.0,
      narrative: 'Periodontal scaling and root planing, lower arch (two quadrants) for treatment of generalized severe chronic periodontitis. Localized antimicrobial (Arestin) placed at two sites with probing depths exceeding 6mm following SRP.',
      status: 'approved',
      submittedDate: '2023-04-08',
      approvedAmount: 656.0,
      denialReason: null,
    },
    {
      id: 'claim-003',
      patientId: 'pat-003',
      insurancePlanId: 'plan-003',
      appointmentId: 'appt-003',
      claimDate: '2024-01-12',
      procedureCodes: 'D1110,D0274',
      totalAmount: 195.0,
      narrative: 'Adult prophylaxis. Bitewing radiographs (4 images) for caries detection — patient on annual radiograph protocol.',
      status: 'approved',
      submittedDate: '2024-01-12',
      approvedAmount: 195.0,
      denialReason: null,
    },
    {
      id: 'claim-004',
      patientId: 'pat-004',
      insurancePlanId: 'plan-004',
      appointmentId: 'appt-004',
      claimDate: '2023-05-24',
      procedureCodes: 'D2391',
      totalAmount: 185.0,
      narrative: 'Posterior composite resin restoration, one surface, primary dentition (tooth #14 MO). Carious lesion confirmed radiographically with dentin involvement. Composite resin placed with bonding agent.',
      status: 'submitted',
      submittedDate: '2023-05-25',
      approvedAmount: null,
      denialReason: null,
    },
    {
      id: 'claim-005',
      patientId: 'pat-005',
      insurancePlanId: 'plan-005',
      appointmentId: 'appt-005',
      claimDate: '2023-08-16',
      procedureCodes: 'D2750,D0340',
      totalAmount: 1250.0,
      narrative: 'Crown, porcelain-fused-to-high noble metal, tooth #3. Existing composite with secondary decay and craze line fractures compromising structural integrity — crown indicated to prevent catastrophic cusp fracture. Panoramic radiograph for treatment planning.',
      status: 'pending',
      submittedDate: null,
      approvedAmount: null,
      denialReason: null,
    },
    {
      id: 'claim-006',
      patientId: 'pat-006',
      insurancePlanId: 'plan-006',
      appointmentId: 'appt-006',
      claimDate: '2024-02-07',
      procedureCodes: 'D4910',
      totalAmount: 240.0,
      narrative: 'Periodontal maintenance following active therapy. Full-mouth periodontal charting performed. Probing depths 3-4mm (improved from 5-8mm pre-treatment). Selective scaling with ultrasonic and hand instruments. Patient on 3-month maintenance cycle.',
      status: 'approved',
      submittedDate: '2024-02-08',
      approvedAmount: 216.0,
      denialReason: null,
    },
    {
      id: 'claim-007',
      patientId: 'pat-007',
      insurancePlanId: 'plan-007',
      appointmentId: 'appt-007',
      claimDate: '2023-03-13',
      procedureCodes: 'D0150,D0274,D1110',
      totalAmount: 485.0,
      narrative: 'Comprehensive oral evaluation — new patient. Full-mouth radiographic series. Adult prophylaxis. Multiple restorative needs identified and documented. Treatment plan created and presented to patient.',
      status: 'denied',
      submittedDate: '2023-03-14',
      approvedAmount: 0,
      denialReason: 'Coverage lapsed — member not found in eligibility file at time of service. Please verify coverage dates and resubmit.',
    },
    {
      id: 'claim-008',
      patientId: 'pat-008',
      insurancePlanId: 'plan-008',
      appointmentId: 'appt-008',
      claimDate: '2023-09-30',
      procedureCodes: 'D1110,D0274',
      totalAmount: 215.0,
      narrative: 'Adult prophylaxis with selective hand scaling to address heavy calculus deposits (mandibular anterior calculus bridge). Bitewing radiographs. Polishing with pumice. Fluoride varnish.',
      status: 'submitted',
      submittedDate: '2023-10-01',
      approvedAmount: null,
      denialReason: null,
    },
    {
      id: 'claim-009',
      patientId: 'pat-009',
      insurancePlanId: 'plan-009',
      appointmentId: 'appt-009',
      claimDate: '2023-06-05',
      procedureCodes: 'D4910',
      totalAmount: 240.0,
      narrative: 'Periodontal maintenance — patient on 3-month recall protocol following SRP. Probing depths stable at 3-5mm. BOP reduced to 18%. Selective subgingival debridement with hand instruments.',
      status: 'approved',
      submittedDate: '2023-06-06',
      approvedAmount: 192.0,
      denialReason: null,
    },
    {
      id: 'claim-010',
      patientId: 'pat-010',
      insurancePlanId: 'plan-010',
      appointmentId: 'appt-010',
      claimDate: '2024-01-24',
      procedureCodes: 'D1110,D0274',
      totalAmount: 195.0,
      narrative: 'Adult prophylaxis. Bitewing radiographs — no caries detected. Fluoride varnish applied.',
      status: 'approved',
      submittedDate: '2024-01-25',
      approvedAmount: 195.0,
      denialReason: null,
    },
    {
      id: 'claim-011',
      patientId: 'pat-011',
      insurancePlanId: 'plan-011',
      appointmentId: 'appt-011',
      claimDate: '2023-02-10',
      procedureCodes: 'D4341,D4381,D0274',
      totalAmount: 1100.0,
      narrative: 'Periodontal SRP, upper arch (two quadrants) for advanced chronic periodontitis. Arestin placed at 4 sites with probing depths >6mm. Bitewing radiographs for monitoring. Patient medical complexity includes uncontrolled DM2 and active tobacco use.',
      status: 'approved',
      submittedDate: '2023-02-13',
      approvedAmount: 880.0,
      denialReason: null,
    },
    {
      id: 'claim-012',
      patientId: 'pat-012',
      insurancePlanId: 'plan-012',
      appointmentId: 'appt-012',
      claimDate: '2024-03-04',
      procedureCodes: 'D1110,D0274',
      totalAmount: 175.0,
      narrative: 'Adult prophylaxis. Bitewing radiographs — incipient lesions noted #30, #31 MO — monitoring protocol initiated. Fluoride varnish applied. Oral hygiene instruction provided.',
      status: 'draft',
      submittedDate: null,
      approvedAmount: null,
      denialReason: null,
    },
    // Additional claims to make dashboard interesting
    {
      id: 'claim-013',
      patientId: 'pat-005',
      insurancePlanId: 'plan-005',
      appointmentId: 'appt-015',
      claimDate: '2026-03-25',
      procedureCodes: 'D2750',
      totalAmount: 1100.0,
      narrative: 'Crown seat appointment — porcelain-fused-to-metal crown #3 seated with permanent cement. Occlusion verified.',
      status: 'pending',
      submittedDate: null,
      approvedAmount: null,
      denialReason: null,
    },
    {
      id: 'claim-014',
      patientId: 'pat-007',
      insurancePlanId: 'plan-007',
      appointmentId: 'appt-007',
      claimDate: '2026-03-28',
      procedureCodes: 'D2391,D2392',
      totalAmount: 425.0,
      narrative: 'Composite restorations #28 DO and #30 MO. Two-surface restorations with dentin bonding agent.',
      status: 'submitted',
      submittedDate: '2026-03-29',
      approvedAmount: null,
      denialReason: null,
    },
  ];

  for (const c of claimData) {
    await prisma.insuranceClaim.upsert({ where: { id: c.id }, update: c, create: c });
  }
  console.log(`Created ${claimData.length} insurance claims`);

  // ─── Balance Records ───────────────────────────────────────────────────────
  const balanceData = [
    {
      id: 'bal-001',
      patientId: 'pat-001',
      amount: 215.0,
      dueDate: '2024-02-15',
      lastPaymentDate: '2023-10-01',
      lastPaymentAmount: 95.0,
      statementSent: true,
      statementDate: '2024-01-15',
      collectionStatus: 'overdue_30',
      notes: 'Patient was billed for copay portion of crown prep. Awaiting crown seat payment.',
    },
    {
      id: 'bal-002',
      patientId: 'pat-002',
      amount: 480.5,
      dueDate: '2023-11-01',
      lastPaymentDate: '2023-07-15',
      lastPaymentAmount: 200.0,
      statementSent: true,
      statementDate: '2023-10-15',
      collectionStatus: 'overdue_90',
      notes: 'Patient owes balance on SRP treatment. Multiple statements sent.',
    },
    {
      id: 'bal-004',
      patientId: 'pat-004',
      amount: 135.0,
      dueDate: '2024-03-01',
      lastPaymentDate: null,
      lastPaymentAmount: null,
      statementSent: false,
      statementDate: null,
      collectionStatus: 'current',
      notes: 'Patient portion for composite restoration after insurance.',
    },
    {
      id: 'bal-005',
      patientId: 'pat-005',
      amount: 650.75,
      dueDate: '2023-12-15',
      lastPaymentDate: '2023-09-20',
      lastPaymentAmount: 350.0,
      statementSent: true,
      statementDate: '2023-12-01',
      collectionStatus: 'overdue_60',
      notes: 'Crown prep balance + outstanding from previous visits. Patient on payment plan arrangement.',
    },
    {
      id: 'bal-007',
      patientId: 'pat-007',
      amount: 320.0,
      dueDate: '2023-06-01',
      lastPaymentDate: null,
      lastPaymentAmount: null,
      statementSent: true,
      statementDate: '2023-05-20',
      collectionStatus: 'collections',
      notes: 'Claim denied — insurance lapsed at time of service. Patient balance for full charges. Sent to collections 2023-09-01.',
    },
    {
      id: 'bal-008',
      patientId: 'pat-008',
      amount: 95.0,
      dueDate: '2024-04-01',
      lastPaymentDate: null,
      lastPaymentAmount: null,
      statementSent: false,
      statementDate: null,
      collectionStatus: 'current',
      notes: 'Copay owed for cleaning and x-rays pending insurance processing.',
    },
    {
      id: 'bal-011',
      patientId: 'pat-011',
      amount: 890.0,
      dueDate: '2023-06-15',
      lastPaymentDate: '2023-03-01',
      lastPaymentAmount: 500.0,
      statementSent: true,
      statementDate: '2023-05-15',
      collectionStatus: 'overdue_90',
      notes: 'Annual maximum exhausted. Patient responsible for remainder of SRP treatment. Payment arrangement in place but payments stopped.',
    },
  ];

  for (const b of balanceData) {
    await prisma.balance.upsert({ where: { id: b.id }, update: b, create: b });
  }
  console.log(`Created ${balanceData.length} balance records`);

  // ─── Recall Tasks ─────────────────────────────────────────────────────────
  const recallData = [
    {
      id: 'recall-001',
      patientId: 'pat-002',
      lastHygieneDate: '2023-04-05',
      recallDueDate: '2023-10-05',
      daysOverdue: 180,
      contactAttempts: 2,
      lastContactDate: '2024-01-15',
      status: 'pending',
      suggestedMessage: 'Hi Robert, this is Bright Smiles Dental. You are overdue for your periodontal maintenance appointment. Given your perio history, keeping up with regular maintenance is important. Please call us at (312) 555-0100 or reply to schedule.',
    },
    {
      id: 'recall-002',
      patientId: 'pat-004',
      lastHygieneDate: '2023-05-22',
      recallDueDate: '2023-11-22',
      daysOverdue: 132,
      contactAttempts: 3,
      lastContactDate: '2024-01-28',
      status: 'pending',
      suggestedMessage: 'Hi Thomas! We miss seeing you at Bright Smiles. You\'re overdue for your 6-month cleaning and check-up. Text back or call (312) 555-0100 to schedule — we have evening slots available!',
    },
    {
      id: 'recall-003',
      patientId: 'pat-007',
      lastHygieneDate: '2023-03-11',
      recallDueDate: '2023-09-11',
      daysOverdue: 204,
      contactAttempts: 1,
      lastContactDate: '2024-02-05',
      status: 'pending',
      suggestedMessage: 'Dear Patricia, you are overdue for your dental cleaning and examination. We also have incomplete treatment on file that we would like to discuss with you. Please contact Bright Smiles at (312) 555-0100 at your earliest convenience.',
    },
    {
      id: 'recall-004',
      patientId: 'pat-009',
      lastHygieneDate: '2023-06-03',
      recallDueDate: '2023-09-03',
      daysOverdue: 213,
      contactAttempts: 4,
      lastContactDate: '2024-01-30',
      status: 'pending',
      suggestedMessage: 'Susan, this is your friendly reminder from Bright Smiles Dental — you\'re due for your quarterly periodontal maintenance. As a perio maintenance patient, regular visits are important. Please call (312) 555-0100 to schedule.',
    },
    {
      id: 'recall-005',
      patientId: 'pat-011',
      lastHygieneDate: '2023-02-08',
      recallDueDate: '2023-05-08',
      daysOverdue: 330,
      contactAttempts: 5,
      lastContactDate: '2024-02-12',
      status: 'pending',
      suggestedMessage: 'Emily, this is Bright Smiles Dental. Given your advanced periodontal condition, you are significantly overdue for your periodontal maintenance appointment. Please call us at (312) 555-0100 as soon as possible. Your dental health is our priority.',
    },
    {
      id: 'recall-006',
      patientId: 'pat-001',
      lastHygieneDate: '2023-07-18',
      recallDueDate: '2024-01-18',
      daysOverdue: 75,
      contactAttempts: 1,
      lastContactDate: '2024-03-01',
      status: 'pending',
      suggestedMessage: 'Hi Margaret, time for your 6-month check-up at Bright Smiles! We\'re also ready to schedule your composite restoration that was recommended at your last visit. Email us or call (312) 555-0100.',
    },
    {
      id: 'recall-007',
      patientId: 'pat-008',
      lastHygieneDate: '2023-09-28',
      recallDueDate: '2024-03-28',
      daysOverdue: 5,
      contactAttempts: 0,
      lastContactDate: null,
      status: 'pending',
      suggestedMessage: 'Kevin, your 6-month cleaning is due at Bright Smiles Dental! Text back or call (312) 555-0100 to schedule. We have early morning slots available.',
    },
    {
      id: 'recall-008',
      patientId: 'pat-003',
      lastHygieneDate: '2024-01-10',
      recallDueDate: '2024-07-10',
      daysOverdue: 0,
      contactAttempts: 0,
      lastContactDate: null,
      status: 'scheduled',
      suggestedMessage: 'Aisha, your next 6-month cleaning is coming up at Bright Smiles. We\'ll send a reminder closer to your appointment date!',
    },
  ];

  for (const r of recallData) {
    await prisma.recallTask.upsert({ where: { id: r.id }, update: r, create: r });
  }
  console.log(`Created ${recallData.length} recall tasks`);

  // ─── Radiograph Studies ────────────────────────────────────────────────────
  const xrayData = [
    {
      id: 'xray-001',
      patientId: 'pat-001',
      date: '2023-07-18',
      type: 'Periapical',
      findings: JSON.stringify({
        summary: 'Periapical radiograph #18 obtained for localized sensitivity evaluation.',
        teeth: [
          {
            tooth: 18,
            findings: 'No caries identified. Existing amalgam restoration with intact margins. Periapical region within normal limits. Lamina dura intact. Widened PDL space not present.',
          },
        ],
        boneLoss: 'None identified',
        calculus: 'Mild supragingival calculus mandibular anteriors',
        recommendation: 'Continue monitoring. No acute pathology. Recall radiograph in 12-18 months.',
      }),
      reviewedBy: 'Dr. Sarah Mitchell',
      reviewedDate: '2023-07-18',
      providerNotes: 'Normal periapical — no intervention warranted. Monitor.',
      imageUrl: 'https://placehold.co/600x400/1a1a2e/4fc3f7?text=PA+%2318',
    },
    {
      id: 'xray-002',
      patientId: 'pat-002',
      date: '2023-04-05',
      type: 'Bitewing Series',
      findings: JSON.stringify({
        summary: 'Four bitewing radiographs for periodontal monitoring and caries assessment.',
        teeth: [
          {
            tooth: 2,
            findings: 'Class II furcation involvement confirmed. Bone loss 35% horizontal pattern on mesial.',
          },
          {
            tooth: 3,
            findings: 'Crestal bone loss 2mm. No caries. Existing amalgam stable.',
          },
          {
            tooth: 14,
            findings: 'Mesial bone loss 30%. Furcation Class I. Existing PFM crown — margin acceptable.',
          },
          {
            tooth: 30,
            findings: 'Moderate bone loss horizontal pattern. No caries. Heavy calculus visible radiographically.',
          },
          {
            tooth: 31,
            findings: 'WNL. No significant pathology.',
          },
        ],
        boneLoss: 'Generalized horizontal pattern lower arch 20-35%',
        calculus: 'Heavy subgingival calculus lower posterior',
        recommendation: 'Consistent with severe chronic periodontitis. SRP initiated. 6-month re-evaluation radiographs recommended.',
      }),
      reviewedBy: 'Dr. James Patel',
      reviewedDate: '2023-04-05',
      providerNotes: 'Severe horizontal bone loss lower arch. Consistent with clinical findings. SRP indicated.',
      imageUrl: 'https://placehold.co/600x400/1a1a2e/4fc3f7?text=BW+Series',
    },
    {
      id: 'xray-003',
      patientId: 'pat-003',
      date: '2024-01-10',
      type: 'Full Mouth Series',
      findings: JSON.stringify({
        summary: 'Full mouth series — 18 films. Annual radiographic survey.',
        teeth: [
          {
            tooth: null,
            findings: 'No caries identified in any quadrant. All existing restorations with intact margins.',
          },
        ],
        boneLoss: 'Crestal bone levels within normal limits throughout. No horizontal or vertical bone loss.',
        calculus: 'None radiographically visible',
        recommendation: 'No radiographic pathology identified. Annual FMX in 3-5 years per ADA guidelines for low-risk patient. Bitewing series annually.',
      }),
      reviewedBy: 'Dr. Sarah Mitchell',
      reviewedDate: '2024-01-10',
      providerNotes: 'Excellent. No pathology. Patient is low caries risk — BWX annually.',
      imageUrl: 'https://placehold.co/600x400/1a1a2e/4fc3f7?text=FMX',
    },
    {
      id: 'xray-004',
      patientId: 'pat-005',
      date: '2023-08-14',
      type: 'Panoramic',
      findings: JSON.stringify({
        summary: 'Panoramic radiograph for treatment planning prior to crown preparation.',
        teeth: [
          {
            tooth: 1,
            findings: 'Third molar partially erupted. No acute pathology.',
          },
          {
            tooth: 3,
            findings: 'Existing MOD composite with secondary caries visible at margins. Pulp horns prominent — RCT may be needed if preparation encroaches on pulp.',
          },
          {
            tooth: 16,
            findings: 'Third molar impacted, horizontal orientation. No pathology. Monitor.',
          },
          {
            tooth: 17,
            findings: 'Partial impaction. No follicular expansion. No pathology.',
          },
          {
            tooth: 32,
            findings: 'Fully impacted, distoangular. No radiographic pathology.',
          },
        ],
        boneLoss: 'Generalized mild crestal bone loss — consistent with age.',
        calculus: 'Moderate calculus deposits posterior regions bilaterally',
        recommendation: 'Third molars #16, #32 should be monitored annually — patient counseled on extraction option. Crown prep #3 — note proximity to pulp; consider pulp exposure risk.',
      }),
      reviewedBy: 'Dr. Sarah Mitchell',
      reviewedDate: '2023-08-14',
      providerNotes: 'Crown prep #3 went well. No pulp exposure. Third molars monitored per patient preference.',
      imageUrl: 'https://placehold.co/600x400/1a1a2e/4fc3f7?text=Panoramic',
    },
    {
      id: 'xray-005',
      patientId: 'pat-007',
      date: '2023-03-11',
      type: 'Full Mouth Series',
      findings: JSON.stringify({
        summary: 'New patient full mouth radiographic survey — 18 films.',
        teeth: [
          {
            tooth: 28,
            findings: 'Carious lesion distal-occlusal, enamel-dentin involvement. No periapical pathology.',
          },
          {
            tooth: 30,
            findings: 'Large existing amalgam with secondary caries visible at margins. Deep lesion approaching pulp. Cold test response prolonged.',
          },
          {
            tooth: 18,
            findings: 'Defective amalgam with open margin — recurrent caries suspected.',
          },
          {
            tooth: 19,
            findings: 'Existing PFM crown — recurrent caries at mesial margin.',
          },
        ],
        boneLoss: 'Mild horizontal bone loss generalized, 10-15%. Consistent with mild periodontitis.',
        calculus: 'Moderate calculus deposits throughout',
        recommendation: 'Treatment priority: #30 (possible RCT or extraction), #28 DO composite, #19 crown replacement, #18 replacement restoration. Comprehensive treatment plan required.',
      }),
      reviewedBy: null,
      reviewedDate: null,
      providerNotes: null,
      imageUrl: 'https://placehold.co/600x400/1a1a2e/4fc3f7?text=FMX+New+Pt',
    },
    {
      id: 'xray-006',
      patientId: 'pat-011',
      date: '2023-02-08',
      type: 'Full Mouth Series',
      findings: JSON.stringify({
        summary: 'Full mouth series for advanced periodontal disease documentation.',
        teeth: [
          {
            tooth: 1,
            findings: 'Horizontal bone loss 65%. Class III furcation. Mobile. Guarded prognosis — possible extraction.',
          },
          {
            tooth: 2,
            findings: 'Bone loss 50%. Furcation Class II. High calculus load.',
          },
          {
            tooth: 3,
            findings: 'Bone loss 45%. Furcation Class II. Endodontic posts visible in both roots.',
          },
          {
            tooth: 14,
            findings: 'Bone loss 40%. Class II furcation. Existing crown margins acceptable.',
          },
          {
            tooth: 15,
            findings: 'Vertical bone defect mesial. 60% bone loss. Poor prognosis.',
          },
          {
            tooth: 16,
            findings: 'Missing. Edentulous space.',
          },
          {
            tooth: 17,
            findings: 'Bone loss 55%. Furcation Class III. Consider extraction.',
          },
        ],
        boneLoss: 'Generalized severe bone loss 40-70%. Consistent with stage III/IV periodontitis.',
        calculus: 'Heavy generalized subgingival calculus throughout',
        recommendation: 'Immediate SRP required. Extractions of #1, #15, #17 may be necessary. Implant consultation when periodontal condition stabilized. Closely coordinate with patient\'s physician regarding DM management.',
      }),
      reviewedBy: 'Dr. James Patel',
      reviewedDate: '2023-02-08',
      providerNotes: 'Stage IV, Grade C periodontitis. Systemic factors (DM, smoking) significantly impacting prognosis. Aggressive treatment plan initiated.',
      imageUrl: 'https://placehold.co/600x400/1a1a2e/4fc3f7?text=FMX+Perio',
    },
    {
      id: 'xray-007',
      patientId: 'pat-010',
      date: '2024-01-22',
      type: 'Bitewing Series',
      findings: JSON.stringify({
        summary: 'Annual bitewing series for caries detection.',
        teeth: [
          {
            tooth: null,
            findings: 'No interproximal caries detected. All existing restorations intact. Crestal bone levels normal.',
          },
        ],
        boneLoss: 'None identified',
        calculus: 'Minimal calculus',
        recommendation: 'Continue annual bitewing radiographs. No treatment indicated.',
      }),
      reviewedBy: 'Dr. Sarah Mitchell',
      reviewedDate: '2024-01-22',
      providerNotes: 'All clear. Annual BWX next year.',
      imageUrl: 'https://placehold.co/600x400/1a1a2e/4fc3f7?text=BWX',
    },
    {
      id: 'xray-008',
      patientId: 'pat-012',
      date: '2024-03-01',
      type: 'Bitewing Series',
      findings: JSON.stringify({
        summary: 'Bitewing series for young adult — caries detection.',
        teeth: [
          {
            tooth: 30,
            findings: 'Incipient lesion mesial-occlusal. D1 — enamel only. Monitor with fluoride protocol.',
          },
          {
            tooth: 31,
            findings: 'Incipient lesion mesial-occlusal. D1 — enamel only. Monitor.',
          },
          {
            tooth: 1,
            findings: 'Deep occlusal groove — sealant candidate.',
          },
          {
            tooth: 16,
            findings: 'Deep fissures — sealant candidate.',
          },
        ],
        boneLoss: 'None. Excellent bone support for age.',
        calculus: 'Minimal',
        recommendation: 'Fluoride varnish applied. Sealants recommended for #1, #16, #17, #32. Monitor incipient lesions #30, #31 — no restoration at this time.',
      }),
      reviewedBy: null,
      reviewedDate: null,
      providerNotes: null,
      imageUrl: 'https://placehold.co/600x400/1a1a2e/4fc3f7?text=BWX+Young+Adult',
    },
  ];

  for (const x of xrayData) {
    await prisma.radiographStudy.upsert({ where: { id: x.id }, update: x, create: x });
  }
  console.log(`Created ${xrayData.length} radiograph studies`);

  // ─── Activity Logs ─────────────────────────────────────────────────────────
  const activityData = [
    {
      id: 'act-001',
      action: 'approve_note',
      entityType: 'ClinicalNote',
      entityId: 'note-001',
      description: 'Clinical note approved for Margaret Harrington by Dr. Mitchell',
      userId: 'demo-user',
      timestamp: new Date('2024-01-02T09:15:00Z'),
      metadata: null,
    },
    {
      id: 'act-002',
      action: 'verify_insurance',
      entityType: 'InsurancePlan',
      entityId: 'plan-003',
      description: 'Insurance verified for Aisha Washington — Aetna Dental',
      userId: 'demo-user',
      timestamp: new Date('2024-01-10T10:30:00Z'),
      metadata: JSON.stringify({ verifiedDate: '2024-01-10' }),
    },
    {
      id: 'act-003',
      action: 'submit_claim',
      entityType: 'InsuranceClaim',
      entityId: 'claim-008',
      description: 'Claim submitted for Kevin Okafor to Aetna Dental',
      userId: 'demo-user',
      timestamp: new Date('2023-10-01T14:20:00Z'),
      metadata: JSON.stringify({ submittedDate: '2023-10-01', totalAmount: 215 }),
    },
    {
      id: 'act-004',
      action: 'send_statement',
      entityType: 'Balance',
      entityId: 'bal-002',
      description: 'Statement sent to Robert Kessler for $480.50',
      userId: 'demo-user',
      timestamp: new Date('2023-10-15T11:00:00Z'),
      metadata: JSON.stringify({ amount: 480.5, statementDate: '2023-10-15' }),
    },
    {
      id: 'act-005',
      action: 'recall_text_sent',
      entityType: 'RecallTask',
      entityId: 'recall-001',
      description: 'Recall text sent to Robert Kessler at (312) 555-0287',
      userId: 'demo-user',
      timestamp: new Date('2024-01-15T09:00:00Z'),
      metadata: JSON.stringify({ phone: '(312) 555-0287' }),
    },
    {
      id: 'act-006',
      action: 'approve_note',
      entityType: 'ClinicalNote',
      entityId: 'note-009',
      description: 'Clinical note approved for Emily Thornton by Dr. Patel',
      userId: 'demo-user',
      timestamp: new Date('2023-02-09T08:30:00Z'),
      metadata: null,
    },
    {
      id: 'act-007',
      action: 'recall_email_sent',
      entityType: 'RecallTask',
      entityId: 'recall-003',
      description: 'Recall email sent to Patricia Monroe at pat.monroe@email.net',
      userId: 'demo-user',
      timestamp: new Date('2024-02-05T10:15:00Z'),
      metadata: JSON.stringify({ email: 'pat.monroe@email.net' }),
    },
    {
      id: 'act-008',
      action: 'verify_insurance',
      entityType: 'InsurancePlan',
      entityId: 'plan-010',
      description: 'Insurance verified for Carlos Ramirez — Delta Dental',
      userId: 'demo-user',
      timestamp: new Date('2024-01-20T13:45:00Z'),
      metadata: JSON.stringify({ verifiedDate: '2024-01-20' }),
    },
    {
      id: 'act-009',
      action: 'generate_note',
      entityType: 'ClinicalNote',
      entityId: 'pat-010',
      description: 'AI SOAP note generated for patient Carlos Ramirez',
      userId: 'demo-user',
      timestamp: new Date('2024-01-22T16:10:00Z'),
      metadata: JSON.stringify({ procedureCode: 'D1110' }),
    },
    {
      id: 'act-010',
      action: 'send_reminder',
      entityType: 'Balance',
      entityId: 'bal-011',
      description: 'Payment reminder sent to Emily Thornton for $890.00',
      userId: 'demo-user',
      timestamp: new Date('2024-02-12T09:30:00Z'),
      metadata: JSON.stringify({ amount: 890.0 }),
    },
    {
      id: 'act-011',
      action: 'submit_claim',
      entityType: 'InsuranceClaim',
      entityId: 'claim-014',
      description: 'Claim submitted for Patricia Monroe to Cigna Dental',
      userId: 'demo-user',
      timestamp: new Date('2026-03-29T14:00:00Z'),
      metadata: JSON.stringify({ submittedDate: '2026-03-29', totalAmount: 425 }),
    },
    {
      id: 'act-012',
      action: 'recall_contact',
      entityType: 'RecallTask',
      entityId: 'recall-005',
      description: 'Contact attempt #5 logged for Emily Thornton',
      userId: 'demo-user',
      timestamp: new Date('2024-02-12T08:00:00Z'),
      metadata: JSON.stringify({ contactDate: '2024-02-12', attempts: 5 }),
    },
    {
      id: 'act-013',
      action: 'approve_note',
      entityType: 'ClinicalNote',
      entityId: 'note-006',
      description: 'Clinical note approved for David Nguyen by Dr. Patel',
      userId: 'demo-user',
      timestamp: new Date('2024-02-06T10:00:00Z'),
      metadata: null,
    },
    {
      id: 'act-014',
      action: 'review_radiograph',
      entityType: 'RadiographStudy',
      entityId: 'xray-003',
      description: 'Full Mouth Series reviewed for Aisha Washington',
      userId: 'demo-user',
      timestamp: new Date('2024-01-10T11:00:00Z'),
      metadata: JSON.stringify({ reviewedBy: 'Dr. Sarah Mitchell', reviewedDate: '2024-01-10' }),
    },
    {
      id: 'act-015',
      action: 'send_statement',
      entityType: 'Balance',
      entityId: 'bal-005',
      description: 'Statement sent to Linda Castillo for $650.75',
      userId: 'demo-user',
      timestamp: new Date('2023-12-01T11:30:00Z'),
      metadata: JSON.stringify({ amount: 650.75, statementDate: '2023-12-01' }),
    },
  ];

  for (const a of activityData) {
    await prisma.activityLog.upsert({ where: { id: a.id }, update: a, create: a });
  }
  console.log(`Created ${activityData.length} activity log entries`);

  console.log('Seed complete!');
}

main()
  .then(async () => {
    await prisma.$disconnect();
  })
  .catch(async (e) => {
    console.error(e);
    await prisma.$disconnect();
    process.exit(1);
  });
